"""empty message

Revision ID: 869a8e6d7305
Revises: 23af16da99c4
Create Date: 2024-04-24 16:43:02.348062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869a8e6d7305'
down_revision = '23af16da99c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_column('return_date')
        batch_op.drop_column('borrow_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrow_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
